---

- hosts: all
  become: true
  tasks:
  
  - name: install Apache2 package
    apt:
      name: apache2

        #  - name: install pickaboo package
        #    apt:
        #      name: pickaboo

  - name: update repo index
    apt:
      update_cache: true

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
